online_store/accounts/urls.py
from django.urls import path
from .views import (get_login_data,
                    get_signup_data)
app_name = "accounts-app"
urlpatterns = [
    path('login/', get_login_data, name='login'),
    path('signup/', get_signup_data, name='signup')
    # path('thanks/', thanks, name='loged'),
]

online_store/home/urls.py
from django.urls import path
from .views import (init,
                    welcome)

app_name = 'home-app'

urlpatterns = [
    path('init/', init, name='init'),
    path('welcome/<int:pk>', welcome, name='welcome'),
    # path('registered/', registered, name='registered'),
]

online_store/online_store/urls.py
from django.contrib import admin
from django.urls import (path,
                         include)
from .views import init_page

app_name = 'main-app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', init_page, name='init-page'),
    path('accounts/', include('accounts.urls', namespace='accounts-app')),
    path('home/', include('home.urls', namespace='home-app')),
]

online_store/accounts/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.id} - {self.username}"

class PhoneNumber(models.Model):
    USA = "+1"
    CO = "+57"
    PREFIX_CHOICES = [
        (USA, "United States"),
        (CO, "Colombia"),
    ]

    country = models.CharField(max_length=3,
                               choices=PREFIX_CHOICES,
                               default=CO)
    phone_number = models.CharField(max_length=30)
    owner = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.country} {self.phone_number}"

online_store/accounts/forms.py
from django import forms

class LogInForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={# "placeholder": "Username",
                                                             # "style": "width: 200px;",
                                                             "class": "form-control input-widget"}),
                               label="Username",
                               max_length=30)
    password = forms.CharField(widget=forms.PasswordInput(attrs={# "placeholder": "Password",
                                                                 # "style": "width: 200px;",
                                                                 "class": "form-control input-widget"}),
                              label="Password",
                               max_length=100)

class SignUpForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control input-widget"}),
        label="First Name",
        max_length=30
)

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control input-widget"}),
        label = "Last Name",
        max_length=30
)

    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control input-widget"}),
        label="Username",
        max_length=30
)

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control input-widget"}),
        label="Password",
        max_length=100
)

online_store/accounts/views.py
from django.shortcuts import render
from django.http import (HttpResponseRedirect,
                         HttpResponse)
from django.urls import reverse_lazy
from .forms import (LogInForm,
                    SignUpForm)
from .models import User

# Create your views here.
def get_login_data(request):
    if request.method == "POST":
        form = LogInForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user_object = User.objects.filter(username=username, password=password).first()
            if user_object:
                pk = user_object.id
                return HttpResponseRedirect(reverse_lazy("home-app:welcome", kwargs={"pk": pk}))

    else:
        form = LogInForm()

    return render(request=request,
                  template_name="login_form.html",
                  context={"form": form,
                           "failed_login": True})

def get_signup_data(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            if User.objects.filter(username=username, password=password).exists():
                return HttpResponse("There is another user with the same username and password")

            else:
                User.objects.create(first_name=first_name,
                                    last_name=last_name,
                                    username=username,
                                    password=password)
                return HttpResponseRedirect(reverse_lazy("accounts-app:login"))

    else:
        form = SignUpForm()

    return render(request=request,
                  template_name="signup_form.html",
                  context={"form": form})

online_store/home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def init(request):
    return HttpResponse("You are on the init page of the home app")

def welcome(request, pk):
    # return HttpResponse(f"Your id is: {pk}")
    return render(request=request,
                  template_name="welcome_page.html")

online_store/online_store/views.py
from django.shortcuts import render

def init_page(request):
    return render(request=request,
                  template_name="init_page.html",
                  context={})

online_store/accounts/templates/login_form.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Log In</title>
	{% load django_bootstrap5 %}
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	{% bootstrap_messages %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login_form.css' %}">
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

	<!-- FONTS -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400&display=swap" rel="stylesheet">
</head>
<body>
	<!--<script>swal({title: "Failed", "text": "Failed to log in, please verify your credentials", "icon": "error", "button": "Retry"})</script>-->
	<div class="form-container">
		<div class="main-message-container">
			<p class="main-message">
				Welcome Again User
			</p>
		</div>
		<form class="main-form" action="/accounts/login/" method="POST">
			{% csrf_token %}
			{% for field in form %}
				<p class="input-label">{{ field.label }}</p>
				<br>
				{{ field }}
				<br>
			{% endfor %}
			<input class="btn btn-primary submit-button" type="submit" value="Log In"/>
		</form>
	</div>
</body>
</html>

online_store/accounts/templates/signup_form.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Sign Up</title>
	{% load django_bootstrap5 %}
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	{% bootstrap_messages %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/signup_form.css' %}">
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

	<!-- FONTS -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400&display=swap" rel="stylesheet">
</head>
<body>
	<div class="form-container">
		<div class="main-message-container">
			<p class="main-message">
				Sign up to enjoy all the features
			</p>
		</div>
		<form class="main-form" action="/accounts/signup/" method="POST">
			{% csrf_token %}
			{% for field in form %}
				<p class="input-label">{{ field.label }}</p>
				<br>
				{{ field }}
				<br>
			{% endfor %}
			<input class="btn btn-primary submit-button" type="submit" value="Sign Up"/>
		</form>
	</div>
</body>
</html>

online_store/home/templates/welcome_page.html
<!DOCTYPE html>
<html>
<head>
	<title>Welcome</title>
</head>
<body>
	<strong>Welcome user, you can leave to:</strong>
	<br>
	<a href="{% url 'accounts-app:login' %}">Log In</a>
	<br>
	<a href="{% url 'accounts-app:signup' %}">Sign Up</a>
</body>
</html>

online_store/online_store/templates/init_page.html
<!DOCTYPE html>
<html>
<head>
	<title>Welcome</title>
</head>
<body>
	<strong>Welcome user, you can leave to:</strong>
	<br>
	<a href="{% url 'accounts-app:login' %}">Log In</a>
	<br>
	<a href="{% url 'accounts-app:signup' %}">Sign Up</a>
</body>
</html>

online_store/templates/init_page.html
<!DOCTYPE html>
<html>
<head>
	<title>Welcome</title>
</head>
<body>
	<strong>Welcome user, you can leave to:</strong>
	<br>
	<a href="{% url 'accounts:login' %}">Log In</a>
	<br>
	<a href="{% url 'accounts:signup' %}">Sign Up</a>
</body>
</html>

online_store/templates/login_form.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Log In</title>
	{% load django_bootstrap5 %}
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	{% bootstrap_messages %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login_form.css' %}">
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

	<!-- FONTS -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400&display=swap" rel="stylesheet">
</head>
<body>
	{% comment %} {% if failed_login %}
	<script>swal({title: "Failed", "text": "Failed to log in, please verify your credentials", "icon": "error", "button": "Retry"})</script>
	{% endif %} {% endcomment %}
	<div class="form-container">
		<div class="main-message-container">
			<p class="main-message">
				Welcome Again User
			</p>
		</div>
		<form class="main-form" action="/accounts/login/" method="POST">
			{% csrf_token %}
			{% for field in form %}
				<p class="input-label">{{ field.label }}</p>
				<br>
				{{ field }}
				<br>
			{% endfor %}
			<input class="btn btn-primary submit-button" type="submit" value="Log In"/>
		</form>
	</div>
</body>
</html>