simple_blog/simple_blog/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = 'main-app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users-app'))
]

simple_blog/users/urls.py
from django.urls import path
from . import views

app_name = "users-app"

urlpatterns = [
    path("", views.index, name="index-page-view"),
    path("create/", views.create_account, name="create")
]

simple_blog/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
# Create your models here.
class UserAccount(AbstractBaseUser):
    first_name = models.CharField(max_length=30, blank=False, null=False)
    last_name = models.CharField(max_length=30, blank=False, null=False)
    username = models.CharField(max_length=50, blank=False, null=False)
    password = models.CharField(max_length=256, blank=False, null=False)

    def __str__(self):
        return f"{self.id} - {self.username}"

class UserProfile(models.Model):
    account = models.OneToOneField(UserAccount, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.id} - {self.account.username}"

simple_blog/users/forms.py
from django import forms

class AccountCreationForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
          "class": "creation-form-field"
        }),
        label="First Name",
        max_length=30
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
          "class": "creation-forms-field"
        }),
        label="Last Name",
        max_length=30
    )

    username = forms.CharField(
        widget=forms.TextInput(attrs={
          "class": "creation-form-field"
        }),
        label="Username",
        max_length=50
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
          "class": "creation-form-field"
        }),
        label="Password",
        max_length=256
    )

simple_blog/users/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms
from .models import UserAccount, UserProfile

# Create your views here.
def index(request):
    return render(request=request,
                  template_name="users-index-page.html",
                  context={})

def create_account(request):
    if request.method == "GET":
        form = forms.AccountCreationForm()
        return render(request=request,
                      template_name="create_account.html",
                      context={"form": form})

    if request.method == "POST":
        form = forms.AccountCreationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            ua = UserAccount(
                first_name=first_name,
                last_name=last_name,
                username=username,
                password=password)

            up = UserProfile(account=ua)
            ua.save()
            up.save()
            return HttpResponse("Axcount Created Successfully")

simple_blog/templates/create_account.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>
			Create Account
		</title>
	</head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<body>
		<strong>
			This is the form to create an account on our blog
		</strong>
		<hr>
		<div class="creation-form-container container">
			<form action="{% url 'users-app:create' %}" method="POST">
			{% csrf_token %}
			{% for field in form %}
				<div class="row">
					<div class="col">
						<p class="creation-form-field-label">
							{{ field.label }}
						</p>
					</div>
				</div>
				<!-- <br> -->
				<div class="row">
					<div class="col">
						{{ field }}
					</div>
				</div>
				<!-- <br> -->
			{% endfor %}
				<div class="row">
					<div class="col">
						<input type="submit" value="Create Account" />
					</div>
				</div>
			</form>
		</div>
	</body>
</html>

simple_blog/templates/users-index-page.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>
			Index Page
		</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	</head>
	<body>
		<strong>
			Hello user, this is the index page for the accounts administration
		</strong>
		<hr>
		<a href="{% url 'users-app:create' %}">
			Create Account
		</a>
	</body>
</html>