blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import to_index

app_name = 'core-app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', to_index),
    path('accounts/', include('users.urls', namespace='users-app')),
    path('home/', include('home.urls', namespace='home-app')),
]

blog/home/urls.py
from django.urls import path
from .views import (logout_user,
                    IndexView,
                    SearchView,
                    UserView,
                    CreatePostView)

app_name = 'home-app'

urlpatterns = [
    path('', IndexView.as_view(), name='index-view'),
    path('search/', SearchView.as_view(), name="search-view"),
    path('user/username=<str:username>', UserView.as_view(), name='user-view'),
    path('create-post/', CreatePostView.as_view(), name='create-post-view'),
    path('exit/', logout_user, name='logout-view')
]

blog/templates/include/nav-bar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    {% comment %} <a class="navbar-brand" href="{% url 'home-app:index-view' %}"><img src="{% static 'img/blog-icon.png' %}" width="20" height="20"></a> {% endcomment %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/default-profile-photo.png' %}" width="25" height="25" alt="Profile Photo" />
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'home-app:user-view' username=user.get_username %}">Your Profile</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="#">Something else here</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'home-app:logout-view' %}">Log Out</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="{% url 'home-app:create-post-view' %}" class="nav-link active me-1">
            Create
          </a>
        </li>
        <li class="nav-item">
          <div class="d-inline-flex">
            <input class="form-control px-2 me-2" type="text" name="query" placeholder="Search something">
            <input class="btn btn-outline-success" type="submit" value="Search">
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>